# Proxy in front of MiningCore Web UI: inject script to remove Referral/Support and replace copyright
upstream webui_backend {
  server web:8080;
}

server {
  listen 8080;
  server_name _;

  location /public-pool-btc-inject.js {
    alias /etc/nginx/inject.js;
    add_header Content-Type application/javascript;
  }

  location / {
    proxy_pass http://webui_backend;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Accept-Encoding "";
    proxy_buffering on;
    proxy_buffer_size 128k;
    proxy_buffers 4 256k;
    proxy_busy_buffers_size 256k;
    proxy_max_temp_file_size 0;
    sub_filter '</body>' '<script src="/public-pool-btc-inject.js"></script></body>';
    sub_filter_once off;
    sub_filter_types text/html;
  }
}
